services:
  domify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: domify-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      # Las siguientes variables se configurarán desde Portainer:
      # PUBLIC_SUPABASE_URL: 
      # PUBLIC_SUPABASE_ANON_KEY: 
      # PRIVATE_SUPABASE_SERVICE_ROLE_KEY: 
      # SMTP_HOST: 
      # SMTP_PORT: 
      # SMTP_USER: 
      # SMTP_PASS: 
      # FROM_EMAIL: 
    restart: unless-stopped
    networks:
      - domify-network

networks:
  domify-network:
    driver: bridge
