import { json, type RequestHandler } from '@sveltejs/kit';
import { getSupabaseUrl, getSupabaseServiceRoleKey } from '$lib/env-utils';

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_SERVICE_ROLE_KEY = getSupabaseServiceRoleKey();

export const POST: RequestHandler = async ({ locals: { supabaseAdmin } }) => {
	try {
		console.log('🔧 Creando tabla provider_categories...');

		// Usar la API REST de Supabase para ejecutar SQL directamente
		const sqlQuery = `
			CREATE TABLE IF NOT EXISTS public.provider_categories (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				provider_profile_id BIGINT REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
				category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
				created_at TIMESTAMPTZ DEFAULT NOW(),
				UNIQUE(provider_profile_id, category_id)
			);
			
			-- Habilitar RLS
			ALTER TABLE public.provider_categories ENABLE ROW LEVEL SECURITY;
			
			-- Política de lectura pública
			CREATE POLICY IF NOT EXISTS "Permitir lectura pública de provider_categories"
				ON public.provider_categories FOR SELECT
				USING (true);
				
			-- Política de inserción para service_role
			CREATE POLICY IF NOT EXISTS "Permitir inserción service_role provider_categories"
				ON public.provider_categories FOR INSERT
				WITH CHECK (true);
				
			-- Política de eliminación para service_role
			CREATE POLICY IF NOT EXISTS "Permitir eliminación service_role provider_categories"
				ON public.provider_categories FOR DELETE
				USING (true);
		`;

		// Ejecutar SQL via rpc si existe la función, o vía REST SQL endpoint
		const response = await fetch(`${SUPABASE_URL}/rest/v1/rpc/exec_sql`, {
			method: 'POST',
			headers: {
				'apikey': SUPABASE_SERVICE_ROLE_KEY,
				'Authorization': `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({ sql: sqlQuery })
		});

		if (!response.ok) {
			// Si exec_sql no existe, intentar con el endpoint SQL de Supabase Management API
			console.log('⚠️ exec_sql no disponible, intentando vía SQL API...');
			
			// Intentar usando el SQL endpoint de la Management API
			const sqlResponse = await fetch(`${SUPABASE_URL}/pg/query`, {
				method: 'POST',
				headers: {
					'apikey': SUPABASE_SERVICE_ROLE_KEY,
					'Authorization': `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({ query: sqlQuery })
			});

			if (!sqlResponse.ok) {
				const errorText = await sqlResponse.text();
				console.error('❌ Error SQL API:', errorText);
				
				// Último intento: crear mediante supabase.rpc con una función genérica
				// Si tampoco funciona, indicar al usuario que debe ejecutar el SQL manualmente
				return json({
					success: false,
					message: 'No se pudo ejecutar el SQL automáticamente. Ejecuta este SQL manualmente en Supabase Dashboard > SQL Editor:',
					sql: sqlQuery,
					error: errorText
				});
			}
			
			const sqlResult = await sqlResponse.json();
			console.log('✅ Tabla creada vía SQL API:', sqlResult);
		} else {
			const result = await response.json();
			console.log('✅ Tabla creada vía exec_sql:', result);
		}

		// Verificar que la tabla se creó correctamente intentando hacer un SELECT
		const { data: testData, error: testError } = await supabaseAdmin
			.from('provider_categories')
			.select('*')
			.limit(1);

		if (testError) {
			return json({
				success: false,
				message: 'La tabla aún no existe después del intento. Ejecuta este SQL manualmente:',
				sql: sqlQuery,
				error: testError.message
			});
		}

		return json({
			success: true,
			message: '✅ Tabla provider_categories creada exitosamente',
			data: testData
		});

	} catch (error) {
		console.error('💥 Error:', error);
		return json({
			success: false,
			error: error instanceof Error ? error.message : 'Error desconocido'
		}, { status: 500 });
	}
};

// GET para verificar si la tabla existe
export const GET: RequestHandler = async ({ locals: { supabaseAdmin } }) => {
	try {
		const { data, error } = await supabaseAdmin
			.from('provider_categories')
			.select('*')
			.limit(5);

		if (error) {
			return json({
				exists: false,
				error: error.message,
				hint: 'La tabla provider_categories NO existe. Usa POST para crearla o ejecuta el SQL manualmente.'
			});
		}

		return json({
			exists: true,
			count: data?.length || 0,
			data
		});
	} catch (error) {
		return json({
			exists: false,
			error: error instanceof Error ? error.message : 'Error desconocido'
		});
	}
};
